services:
  server:
    container_name: debug_test_api
    environment:
      - PGUSER=postgres
      - PGHOST=db
      - PGPASSWORD=pass
      - PGDATABASE=library_test
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
  db:
    container_name: debug_test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=library_test
      - POSTGRES_PASSWORD=pass
volumes:
  test_db:
networks:
  default:
    name: debug_test
